- type: job
  id: M14Furer
  name: Фюрер
  description: Вы великий вождь.
  playTimeTracker: M14Furer
  startingGear: SecurityOfficerGear
  icon: "JobIconGydra"
  canBeAntag: true

- type: jobIcon
  parent: JobIcon
  id: JobIconGydra
  icon:
    sprite: _Metro14/Interface/job_icons.rsi
    state: gydra
  jobName: gydravci

- type: playTimeTracker
  id: M14Furer

