- type: job
  id: M14SoldierGydra
  name: Солдат Гидры
  description: Вы великий представитель гидры. Цвет метро.
  playTimeTracker: M14SoldierGydra
  startingGear: M14DefaultZBTGear
  icon: "JobIconGydra"
  canBeAntag: true

- type: playTimeTracker
  id: M14SoldierGydra